ROUTINE %ZAPM.bs.BSCZSHT
%BSCZSHUTDOW //ЗАПУСК ЗАДАНИЙ ПРИ останове СИСТЕМЫ
 ;
 ;    Copyright Serge W. Mikhaylenko
 ;    All Rights Reserved
 ;
 ;
 I $$STOPFTP //ТОРМОЗ МОЕГО FTP СЕРВЕРА
 Q
STOPFTP() //СЕАНС ЗАКРЫТИЯ СЕРВЕРА
 Set ftp=##class(%Net.FtpSession).%New(),$ZT="STOPERR"
 If 'ftp.Connect($$ipS^%ZAPM.bs.BSCp2,"ddr-adm","shutdown_SERVER",22) Write "Not connected",! Quit 0
STOPERR W !,"OK" Q 1     Q
